<nav class="main-nav">
    <ul>
        <li><a href="index.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'index.php' ? 'active' : '' ?>">Home</a></li>
        <li><a href="jobs.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'jobs.php' ? 'active' : '' ?>">Jobs</a></li>
        <li><a href="apply.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'apply.php' ? 'active' : '' ?>">Apply</a></li>
        <li><a href="about.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'about.php' ? 'active' : '' ?>">About</a></li>
        <li><a href="enhancements.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'enhancements.php' ? 'active' : '' ?>">Enhancements</a></li>
        <li><a href="manage.php" class="<?php echo basename($_SERVER['PHP_SELF']) == 'manage.php' ? 'active' : '' ?>">Manager Login</a></li>
    </ul>
    </nav>