<footer class="site-footer">
    <div class="footer-container">
        <div class="footer-about">
        <h3>G.O.A.T Solutions</h3>
        <p>
            Based in Melbourne, GOAT Solutions partners with businesses and individuals to create unparalleled software solutions. Tomorrow's Innovation, Today.
        </p>
        </div>
    
        <!-- Footer navigation -->
        <div class="footer-nav">
        <h3>Quick Links</h3>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="jobs.html">Jobs</a></li>
            <li><a href="apply.html">Apply</a></li>
            <li><a href="about.html">About Us</a></li>
        </ul>
        </div>

        <div class="footer-contact">
        <h3>Contact Us</h3>
        <p>Email: <a href="mailto:info@goatsolutions.com.au">info@goatsolutions.com.au</a></p>
        <p>Phone: +61 5101 0101</p>
        </div>
    </div>

    <div class="footer-bottom">
        <p>&copy; 2025 G.O.A.T & Swinburne University of Technology. All rights reserved.</p>
        <p><a href="https://goat-team-best-team.atlassian.net">Jira</a> | <a href="https://github.com/105928712/goat">GitHub</a></p>
    </div>
</footer>